_wandb:
    value:
        cli_version: 0.21.1
        e:
            grj3nncsswfs2m82w0ignvi5uxp0mrcq:
                codePath: train_carla.py
                codePathLocal: train_carla.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "486875860992"
                        used: "421068021760"
                email: theyanesher@gmail.com
                executable: /home/theyanesh.er/miniconda3/envs/nomad_train/bin/python
                git:
                    commit: 251dcd2ea570491db174048429a480648598eba8
                    remote: https://github.com/theyanesher/flownav.git
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-accce6fe-c908-c93f-b212-4dacacc8c0df
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-181b55fa-18f2-c6ed-493f-7cd6a56b3f02
                host: pop-os
                memory:
                    total: "33583415296"
                os: Linux-6.0.12-76060012-generic-x86_64-with-glibc2.31
                program: /home/theyanesh.er/flownav/train_carla.py
                python: CPython 3.10.8
                root: /home/theyanesh.er/flownav
                startedAt: "2025-09-11T06:01:24.513347Z"
                writerId: grj3nncsswfs2m82w0ignvi5uxp0mrcq
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 83
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 83
            "3":
                - 3
                - 17
            "4": 3.10.8
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
action:
    value:
        max_dist_cat: 20
        min_dist_cat: 3
alpha:
    value: "1e-4"
attn_unet:
    value: false
batch_size:
    value: 1
clipping:
    value: false
cond_predict_scale:
    value: false
context_size:
    value: 4
context_type:
    value: temporal
cyclic_period:
    value: 10
datasets:
    value:
        carla:
            data_folder: /share1/pranjal.paul/carla_flow_data/
            end_slack: 0
            goals_per_obs: 1
            negative_mining: false
            test: /share1/pranjal.paul/carla_flow_data/val/
            train: /share1/pranjal.paul/carla_flow_data/train/
depth:
    value:
        depth_encoder: vits
        dino_layer_idx:
            vits:
                - 2
                - 5
                - 8
                - 11
        out_dim:
            vits: 384
        pool_dim: 64
        weights_path: /home/theyanesh.er/flownav/depth_anything_v2_vits.pth?download=true
distance:
    value:
        max_dist_cat: 20
        min_dist_cat: 0
down_dims:
    value:
        - 64
        - 128
        - 256
encoding_size:
    value: 256
entity:
    value: <YOUR ENTITY>
epochs:
    value: 30
eval_batch_size:
    value: 1
eval_fraction:
    value: 0.25
eval_freq:
    value: 1
goal_mask_prob:
    value: 0
goal_type:
    value: image
gpu_ids:
    value:
        - 0
image_log_freq:
    value: 1000
image_size:
    value:
        - 96
        - 96
learn_angle:
    value: false
len_traj_pred:
    value: 32
lr:
    value: "1e-4"
max_norm:
    value: 1
mha_ff_dim_factor:
    value: 4
mha_num_attention_heads:
    value: 4
mha_num_attention_layers:
    value: 4
model_type:
    value: nomad
normalize:
    value: true
num_images_log:
    value: 8
num_workers:
    value: 4
obs_encoder:
    value: efficientnet-b0
obs_type:
    value: image
optimizer:
    value: adamw
pairwise_test_freq:
    value: 0
plateau_factor:
    value: 0.5
plateau_patience:
    value: 3
print_log_freq:
    value: 500
project_folder:
    value: logs/flownav/flownav_2025_09_11_11_31_23
project_name:
    value: flownav
run_name:
    value: flownav_2025_09_11_11_31_23
scheduler:
    value: cosine
seed:
    value: 0
train:
    value: true
use_wandb:
    value: true
vision_encoder:
    value: nomad_vint
wandb_log_freq:
    value: 10
warmup:
    value: true
warmup_epochs:
    value: 4
